// /** @type {import('tailwindcss').Config} */
module.exports = {
	mode: 'jit',
	content: [
		'./app/**/*.{js,ts,jsx,tsx}',
		'./pages/**/*.{js,ts,jsx,tsx}',
		'./app/*.{js,ts,jsx,tsx}',
		'./components/**/*.{js,ts,jsx,tsx}',
		'./src/**/*.{js,ts,jsx,tsx}',
	],
	theme: {
		extend: {
			colors: {
				'theme-background-color': 'var(--theme-background-color)',
				'theme-side-bg-color': 'var(--theme-side-bg-color)',
				'theme-side-bg-shade': 'var(--theme-side-bg-shade)',
				'theme-active-bg-color': 'var(--theme-active-bg-color)',
				'color-primary': 'var(--color-primary)',
				'color-primary-opacity': 'var(--color-primary-opacity)',
				'color-link-inactive': 'var(--color-link-inactive)',
				'color-link-active': 'var(--color-link-active)',
				'theme-link-bg-active': 'var(--theme-link-bg-active)',
				'color-menu-link-hover': 'var(--color-menu-link-hover)',
				'color-text': 'var(--color-text)',
				'color-default-shadow': 'var(--color-default-shadow)',
				'color-bg-menu': 'var(--color-bg-menu)',
				'color-message': 'var(--color-message)',
				'color-svg': 'var(--color-svg)',
				'color-error': 'var(--color-error)',
				'ico-gradient': 'var(--ico-gradient)',
				'color-meta': 'var(--color-meta)',
				'color-pinned': 'var(--color-pinned)',
				'color-gray': 'var(--color-gray)',
				'color-message-rbga': 'var(--color-message-rbga)',
				'meta-colored': 'var(--meta-colored)',
				'color-border': 'var(--color-border)',
				'color-composer-button': 'var(--color-composer-button)',
				'color-message-shadow': 'var(--color-message-shadow)',
				'color-bg-s-message': 'var(--color-bg-s-message)',
				'borders-color': 'var(--borders-color)',
				'compact-bg-color': 'var(--compact-bg-color)',
				'button-bg-shade-color': 'var(--button-bg-shade-color)',
				'button-bg-regular-shade-color': 'var(--button-bg-regular-shade-color)',
				'pattern-color': 'var(--pattern-color)',
			},
			spacing: {
				'side-header-padding': 'var(--side-header-padding)',
				'side-content-padding': 'var(--side-content-padding)',
				'grid-side-w': 'var(--grid-side-w)',
				'preview-image-w': 'var(--preview-image-w)',
				'preview-image-h': 'var(--preview-image-h)',
				'preview-image-sm-w': 'var(--preview-image-sm-w)',
				'preview-image-sm-h': 'var(--preview-image-sm-h)',
				'preview-padding': 'var(--preview-padding)',
				'ico-margin-right': 'var(--default-margin-right)',
				'small-margin-r': 'var(--default-margin-right)',
				'search-input-h': 'var(--search-input-h)',
				'search-padding': 'var(--search-padding)',
				'tab-padding': 'var(--tab-padding)',
				'tab-paddinglxr': 'var(--tab-padding-lxr)',
				'tab-padding-inner': 'var(--tab-padding-inner)',
				'search-default-h': 'var(--search-default-height)',
				'bttn-smaller-p': 'var(--bttn-smaller-p)',
				'bttn-smaller-w': 'var(--bttn-smaller-w)',
				'bttn-smaller-h': 'var(--bttn-smaller-h)',
				'unread-padding': 'var(--unread-padding)',
				'preview-content-w': 'var(--preview-content-w)',
				'side-content-vh-h': 'var(--side-content-vh-h)',
				'middle-header-p-txb': 'var(--middle-header-p-txb)',
				'middle-header-p-l': 'var(--middle-header-p-l)',
				'middle-header-p-r': 'var(--middle-header-p-r)',
				'miidle-content-bm-m-b': 'var(--miidle-content-bm-m-b)',
				'middle-message-bottom': 'var(--middle-message-bottom)',
				'middle-content-bottom': 'var(--middle-content-bottom)',
				'middle-content-height': 'var(--middle-content-height)',
				'right-col-w': 'var(--right-col-w)',
				'message-container-w': 'var(--message-container-w)',
				'message-translate-percent': 'var(--message-translate-percent)',
				'message-input-p': 'var(--message-input-p)',
				'message-input-p-txb': 'var(--message-input-p-txb)',
				'message-control-pos-l': 'var(--message-control-pos-l)',
				'message-control-pos-r': 'var(--message-control-pos-r)',
				'message-mic-control-wxh': 'var(--message-mic-control-wxh)',
				's-message-m-b': 'var(--s-message-m-b)',
				's-message-out-p': 'var(--s-message-out-p)',
				'user-ico-wrapper-p': 'var(--user-ico-wrapper-p)',
				'user-ico-wrapper-inner-m': 'var(--user-ico-wrapper-inner-m)',
				'personal-input-padding': 'var(--personal-input-padding)',
				'auth-height': 'var(--auth-height)',
				'spinner-size': 'var(--spinner-size)',
				'screen-dvh': 'var(--screen-dvh)',
				'max-file-upload-h': 'var(--max-file-upload-h)',
			},
			scale: {
				'default-font-weight': 'var(--default-font-weight)',
			},
			display: {
				'arrow-back': 'var(--arrow-back)',
			},
			fontSize: {
				'default-font-size': [
					'var(--default-font-size)',
					{
						lineHeight: 'var(--default-line-height)',
						fontWeight: 'var(--default-font-weight)',
					},
				],
				'small-text-size': 'var(--small-text-size)',
				'small-ltime-fs': 'var(--small-ltime-fs)',
				'tab-font-size': 'var(--tab-font-size)',
				'default-pin-size': 'var(--default-pin-size)',
				'send-status-ico-wxh': 'var(--send-status-ico-wxh)',
				'large-font-size': 'var(--large-font-size)',
				'composer-text-size': 'var(--composer-text-size)',
				'message-control-fs': 'var(--message-control-fs)',
				'message-text-size': 'var(--message-text-size)',
				's-message-fs': 'var(--s-message-fs)',
			},
			fontWeight: {
				'tab-font-w': 'var(--tab-font-w)',
			},
			gridTemplateColumns: {
				'grid-side-medium': 'var(--grid-side-medium)',
				's-message-grid-t-col': 'var(--s-message-grid-t-col)',
			},
			backgroundImage: {
				'chat-bg-pattern':
					'url(https://web.telegram.org/a/chat-bg-pattern-dark.ad38368a9e8140d0ac7d.png)',
				'spinner-blue': 'var(--spinner-blue)',
				'spinner-black': 'var(--spinner-black)',
				'spinner-white': 'var(--spinner-white)',
				'spinner-green': 'var(--spinner-green)',
				'spinner-yellow': 'var(--spinner-yellow)',
				'spinner-gray': 'var(--spinner-gray)',
				'spinner-light-blue': 'var(--spinner-light-blue)',
			},
			afterBgContent: {
				backgroundImage:
					'url(https://web.telegram.org/a/chat-bg-pattern-dark.ad38368a9e8140d0ac7d.png)',
			},
			backgroundSize: {
				'content-bg-image-size': 'var(--bg-image-size)',
			},
			boxShadow: {
				'side-nav-shadow': 'var(--side-nav-shadow)',
				'middle-light-shadow': 'var(--middle-light-shadow)',
				'message-shadow': 'var(--message-shadow)',
				'compact-menu-shadow': 'var(--compact-menu-shadow)',
				'modal-dialog-shadow': 'var(--modal-dialog-shadow)',
			},
			borderRadius: {
				'default-border-radius': 'var(--default-border-radius)',
				'search-border-r': 'var(--search-border-r)',
				'border-radius-message-small': 'var(--border-radius-message-small)',
				'message-border-radius': 'var(--message-border-radius)',
				's-message-br-tb-lr': 'var(--s-message-br-tb-lr)',
			},
			borderWidth: {
				'border-width': 'var(--border-width)',
			},
			maxWidth: {
				'message-container-max-w': 'var(--message-container-max-w)',
				's-message-max-w': 'var(--s-message-max-w)',
			},
		},
	},
	plugins: [],
};
