import '../globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Auth page',
	description: 'Generated by create next app',
};

export default function AuthLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<div className="flex pt-[5%] justify-center bg-theme-side-bg-color h-auth-height w-full">
			{children}
		</div>
	);
}
